services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - type: volume
        source: mongodb-volume-data
        target: /data/db
    networks:
      - pooky-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "yourpassword"]
    networks:
      - pooky-network

  cqrs-server:
    build: .
    container_name: pooky-cqrs-server
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - mongodb
      - redis
    networks:
      - pooky-network

networks:
  pooky-network:
    driver: bridge

volumes:
  mongodb-volume-data:
  redis-data:
